### ISSUE TITLE
IntersectionObserver is not defined in Angular 18

### ISSUE THREAD

**Issue by yalesnikov** [daelmaak/ngx-gallery#107]
I have an error with Ngx Gallery in Angular 18. Will you update "@daelmaak/ngx-gallery": "^3.0.4" ?

```
ERROR ReferenceError: IntersectionObserver is not defined
    at _ThumbsComponent.observeArrows (eval at instantiateModule (/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:52905:24), <anonymous>:684:32)
    at Timeout.eval (eval at instantiateModule (/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:52905:24), <anonymous>:585:16)
    at Timeout.timer (eval at instantiateModule (/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:52905:24), <anonymous>:1853:27)
    at _ZoneDelegate.invokeTask (eval at instantiateModule (node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:52905:24), <anonymous>:339:171)
    at eval (eval at instantiateModule (node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:52905:24), <anonymous>:17015:49)
    at AsyncStackTaggingZoneSpec.onInvokeTask (eval at instantiateModule (/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:52905:24), <anonymous>:17015:30)
    at _ZoneDelegate.invokeTask (eval at instantiateModule (/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:52905:24), <anonymous>:339:54)
    at Object.onInvokeTask (eval at instantiateModule (/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:52905:24), <anonymous>:17205:25)
    at _ZoneDelegate.invokeTask (eval at instantiateModule (/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:52905:24), <anonymous>:339:54)
    at ZoneImpl.runTask (eval at instantiateModule (/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:52905:24), <anonymous>:147:37)
```

**Comment by pappkamerad** [comment]
I also just ran into this. it happens when doing SSR with `thumbsArrows` set to true

**Comment by yalesnikov** [comment]
I think it happens because Angular use hydration and new build systems in lasts versions. This error I see with dev mode.

**Comment by yalesnikov** [comment]
> I also just ran into this. it happens when doing SSR with `thumbsArrows` set to true

I think it happens because Angular use hydration and new build systems in lasts versions. This error I see with dev mode.

**Comment by daelmaak** [comment]
Thanks for the issue guys, fixed in https://github.com/daelmaak/ngx-gallery/releases/tag/v3.1.0.
